# Generated by Django 2.1.5 on 2019-01-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190125_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='get_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='give_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
